### ISSUE TITLE
Show how to trigger the `shield` rule in the `Node.js + express` getting started guide

### ISSUE THREAD

**Issue by e-moran** [arcjet/arcjet-docs#179]
The Node.js + Express getting started guide shows how to trigger both the `tokenBucket` and `detectBot` rules. It would be nice to show an example of how to trigger shield.

**Comment by morekid** [comment]
We might want to explain that's the case if we elaborate on the rules a little, like suggested in https://github.com/arcjet/arcjet-docs/issues/181.
