### ISSUE TITLE
Add instructions for creating a new project

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-docs#251]
In each framework get started guide, add a link to their docs showing how to create a new project for devs who want to start from scratch.

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @davidmytton , so basically we just have to add links to respective framework's docs for setting up the project ? Let me know if I misunderstood something. Thanks :)

**Comment by davidmytton** [comment]
Hi @Muhammad-Owais-Warsi , that could be an option, but for Next.js for example I would include the steps described at https://nextjs.org/docs/app/getting-started/installation#automatic-installation

**Comment by Muhammad-Owais-Warsi** [comment]
I understand. Similarly, we can include steps for other frameworks as well. Can I take up this issue, or is someone already working on it?

**Comment by davidmytton** [comment]
You're welcome to open a PR and contribute this fix. I suggest doing 1 framework first and then opening a draft PR so we can review the approach, then when we're happy you can do the others.

**Comment by Muhammad-Owais-Warsi** [comment]
> You're welcome to open a PR and contribute this fix. I suggest doing 1 framework first and then opening a draft PR so we can review the approach, then when we're happy you can do the others.

That's great, as you've already mentioned about Nextjs, I'll start with that only. I'll update you with progress. Thnaks.

**Comment by Muhammad-Owais-Warsi** [comment]
Hey @davidmytton , I've made few changes. Please let me know the changes. For now I've mentioned `0` as the starting step.

![Image](https://github.com/user-attachments/assets/91374041-6662-461c-8c92-dcf215618259)

**Comment by blaine-arcjet** [comment]
I think we should only link to getting started information for a framework. Keeping guides for initializing projects is burden we cannot afford to maintain as changes happen in those frameworks.

**Comment by Muhammad-Owais-Warsi** [comment]
> I think we should only link to getting started information for a framework. Keeping guides for initializing projects is burden we cannot afford to maintain as changes happen in those frameworks.

That's an excellent point @blaine-arcjet . I'll change and simply put the link instead. Thanks!

**Comment by davidmytton** [comment]
Let's go with a middle ground -  how about adding the set up command, then a link to the framework docs to complete the process? I.e. in the Next.js case we'd keep `npx create-next-app@latest` but then link out to their docs.

Having it as step 0 is good.

**Comment by Muhammad-Owais-Warsi** [comment]
Let me know the changes. Thanks :)
![Image](https://github.com/user-attachments/assets/375a5bf5-3b9e-400f-9e9f-ea6a8af53489)

**Comment by davidmytton** [comment]
Looks good. You'll also need to manually add it to the table of contents block in the front matter.

**Comment by davidmytton** [comment]
Yes please. Feel free to open a PR so we can review.

**Comment by Muhammad-Owais-Warsi** [comment]
Raise the PR #318

**Comment by davidmytton** [comment]
Fixed by https://github.com/arcjet/arcjet-docs/pull/318
