### ISSUE TITLE
Property 'getBody' is missing in type '{}' but required in type 'ArcjetAdapterContext'

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-docs#27]
The docs example in https://github.com/arcjet/arcjet-docs/blob/9d790cecc997e8d4b0148b29a8e462ba7c0138ed/src/content/docs/reference/snippets/nodejs/RequestFields.ts#L45 

no longer works with the latest SDK release:

```
 Property 'getBody' is missing in type '{}' but required in type 'ArcjetAdapterContext'.
```

**Comment by e-moran** [comment]
I guess to fix it properly you'd need to add in the body package and use that to pull the data from the `IncomingMessage`. Technically they could just stub it if they're not going to use sensitiveInfo, but documenting that could be a footgun.

**Comment by blaine-arcjet** [comment]
> Technically they could just stub it if they're not going to use sensitiveInfo, but documenting that could be a footgun.

Arcjet core doesn't need to be easy to use, as users should be using adapters. I think we just show using `@arcjet/body` here.

**Comment by e-moran** [comment]
Yeah makes sense! I'll open a PR showing how to use `@arcjet/body`.
