### ISSUE TITLE
Typo in Example Code – Full Stop Instead of Comma

### ISSUE THREAD

**Issue by mynk2611** [arcjet/arcjet-docs#344]
small typo in the Identifying Bots section of the documentation

<img width="772" alt="Image" src="https://github.com/user-attachments/assets/228e5a7b-bbae-44d0-9024-0edef78ef856" />

expected comma after "GOOGLE_CRAWLER"

**Comment by davidmytton** [comment]
Thanks for reporting @mynk2611 !
